### ISSUE TITLE
检测差异的提交文件需要在stage区域？

### ISSUE THREAD

**Issue by aliu927** [yangziwen/diff-check#1]
现象：git commit时触发检测差异部分是stage区域的文件与HEAD进行比较，也就是说需要先执行git add .才能做diff；为啥不直接用git status的diff呢？

**Comment by yangziwen** [comment]
你好，谢谢你关注这个工具。

在结合git使用本工具时，如果存在未通过检查的代码，则工具会阻断当前commit操作。

在开发过程中，我们不一定每次都会commit工作区中所有发生了变化的代码。但是如果基于工作区而不是暂存区中的代码变化量进行代码风格或缺陷的检查，则`git commit`时，即使不需要提交某个文件，也必须保证该文件能够通过检查。通常情况下，这样的策略对开发人员并不友好。

目前通过`git commit -a`提交代码时，本工具确实不能有效对代码进行检查。但eclipse, idea等IDE以及其他一些图形化的git工具，在勾选文件commit时，都会先执行add操作，即在使用这些图形化工具commit时，本工具都是可以正常阻断提交问题代码的。

另外，`git commit -a`无法提交新增的文件，同时使用`git add`，可以更好的控制每次`git commit`的粒度，因此即便在使用命令行的情况下，也是更提倡合理使用`git add`的。

**Comment by aliu927** [comment]
我尝试了一下在pre-commit脚本里执行检查之前增加git add命令，结果是没有可检查的文件。
想问一下这块有没有解决方案呢？我把代码下载下来尝试去解决，发现代码和jar包里的代码不一致哈。

**Comment by aliu927** [comment]
“git commit -a 这种Case不能有效对代码检查” 是机制本身决定无法覆盖吗？还是说工具本身不支持这种Case？

**Comment by yangziwen** [comment]
> 我尝试了一下在pre-commit脚本里执行检查之前增加git add命令，结果是没有可检查的文件。
> 想问一下这块有没有解决方案呢？我把代码下载下来尝试去解决，发现代码和jar包里的代码不一致哈。

测试了下，在pre-commit钩子的最前面加上`git add .`后，执行`git commit`时diff-check是可以正常检查暂存区的文件变更并阻塞问题代码提交的。你的尝试没能成功，我估计可能有以下两个原因

- pre-commit文件不是可执行文件，需要通过`chmod +x .git/hooks/pre-commit`添加执行的权限。

- 如果此前按全局方式安装过diff-check(`sh install.sh --global`)，那么install.sh会通过`git config --global core.hooksPath ~/.githooks`全局设置git的钩子目录，此后每个代码库中的`.git/hooks`目录中的钩子将会不起作用。因此你可以将`git add .`命令添加到全局钩子目录中的pre-commit脚本里，或者用`git config --global --unset core.hooksPath`解除全局钩子目录设置后，再在具体的代码库的pre-commit脚本中添加`git add .`命令。

最后，必须说明的是，这种在pre-commit中添加`git add .`命令的做法，并不适合普遍推广。因为这会自动提交工作区中所有发生了变更的文件，而在很多情况下，开发者需要有选择的提交变更文件。

**Comment by yangziwen** [comment]
> “git commit -a 这种Case不能有效对代码检查” 是机制本身决定无法覆盖吗？还是说工具本身不支持这种Case？

据我观察，`git commit -a`命令add文件的效果，似乎只在当前进程中可见。

我在pre-commit的前面添加了`git status`和`sleep 20`这2行命令。然后同时打开两个命令行窗口。在第一个窗口中执行`git commit -a`操作，pre-commit脚本的输出结果显示工作区的文件已被add到了暂存区。但是在sleep命令等待过程中，前往第二个窗口执行`git status`命令，则会发现工作区中的文件是未添加到暂存区的状态。

diff-check是通过java命令启动的进程运行的，所以可能也存在这种可见性的问题。但是这个可见性问题的具体原因，我目前还不清楚。
