### ISSUE TITLE
疑似使用git commit -am指令可能会检查不到新加入的文件

### ISSUE THREAD

**Issue by ljsnake** [yangziwen/diff-check#10]
首先非常感谢能找到你这个类似场景的参照功能。
我实际测试使用中疑似遇到“git commit -am指令可能会检查不到新加入的文件”的情况：
1，先有个java文件已经被git管理着
2，修改java文件，增加违反规则的行
3，使用 git commit -am "some comment"进行提交，发现代码检查被跳过了
操作如下图:
![image](https://user-images.githubusercontent.com/6836113/155667143-2ab8b86a-5295-4293-9a83-976a14feb227.png)
4，为了表达正常使用会有拦截，额外做了后续常规git add加入stage管理之后再git commit -m 提交的操作图：
![image](https://user-images.githubusercontent.com/6836113/155667588-8de756af-77b9-4630-b6e5-2110a8904ef4.png)

不知道你是否遇到过，谢谢。

**Comment by ljsnake** [comment]
貌似在 https://github.com/yangziwen/diff-check/issues/1 里面有部分解释了。抱歉

**Comment by yangziwen** [comment]
多谢关注哈，共同探讨~
