### ISSUE TITLE
关于一些其他方面的问题

### ISSUE THREAD

**Issue by SmallPiedPiper** [yangziwen/diff-check#11]
大佬你好 我在您这个基础上 集成了 公司现有的CI流程执行  目前已经在个别工程里面使用，碰到一些落地价值方面的问题，
如何试用的时候能有一些数据来体现实际的效果？
我自己觉得本身这个插件对团队的影响应该是潜移默化，慢慢提升的，很难找到 一些数据和指标去说明一些问题，
不知道您这边关于这块有没有过思考 想请教下

**Comment by yangziwen** [comment]
你好，感谢支持。你们目前只使用了checkstyle的相关功能，还是也有使用jacoco部分的功能？
有兴趣可以加个联系方式，互相探讨（微信13683258546）

**Comment by SmallPiedPiper** [comment]
目前是只使用过了 checkStyle 因为目前公司里面java coco 和PMD部分的东西 都已经在CI上面具备了，所以checkStyle 是对现在有流程的一个补充，我这边其实是业务研发。是因为组内刚好要做一些CR的规范流程。所以补充了check style的 的能力，
目前我的想法有几个指标
1、从检测出来的问题来计算，检测出来 比较重要的问题，比如 魔法数、java doc ,命名等这些问题，前后代码对比即可衡量效果，提升了代码可读性
2、从检测代码行数、方法长度，等这些 提高了可维护性
sonar 里面有具体对应的指标吗  这块我到是不太熟悉，具体有哪些指标可以 衡量价值
