### ISSUE TITLE
How do I hook diff_checkstyle to maven?

### ISSUE THREAD

**Issue by mettyoung** [yangziwen/diff-check#15]
Hi yangziwen, I really appreciate your work on diff-check. 

Do you know how I can hook diff_checkstyle as a maven goal? I wanted to implement configuration inheritance to avoid tampering google_checks.xml with my custom_checks.xml. 

An example of workaround is:
https://stackoverflow.com/questions/63953276/maven-checkstyle-plugin-with-google-checks-and-4-space-indentsize/67929699#67929699

**Comment by yangziwen** [comment]
Thank you for asking about this.

You can use maven-exec-plugin to hook diff-checkstyle and specify your favorite checks.xml in the arguments section, and I'll provide a completed configuration sample for you after I get off work.

Besides, you can have a look at the [readme](https://github.com/yangziwen/diff-checkstyle/blob/master/README.md) of diff-checkstyle project, which is the predecessor of diff-check, though some parameters are not exactly the same.

**Comment by yangziwen** [comment]
I use the configuration as follows
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.5.0</version>
    <executions>
        <execution>
            <phase>test</phase>
            <goals>
                <goal>java</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
     <executable>java</executable>
     <includeProjectDependencies>false</includeProjectDependencies>
     <includePluginDependencies>true</includePluginDependencies>
     <executableDependency>
         <groupId>io.github.yangziwen</groupId>
         <artifactId>diff-checkstyle</artifactId>
     </executableDependency>
     <mainClass>io.github.yangziwen.checkstyle.Main</mainClass>
     <cleanupDaemonThreads>false</cleanupDaemonThreads>
     <arguments>
         <!-- any parameters supported by the original checkstyle command-line tool -->
         <argument>-c</argument>
         <argument>/custom_checks.xml</argument>
         <argument>${basedir}</argument>
         <argument>--git-dir</argument>
         <argument>${basedir}</argument>
         <!--
         <argument>-f</argument>
         <argument>xml</argument>
         <argument>-o</argument>
         <argument>${project.build.directory}/checkstyle.xml</argument>
         -->
         <argument>--base-rev</argument>
         <!-- pass the base-rev value via the system variable -->
         <argument>${checkstyle.base.rev}</argument>
         <argument>--include-staged-codes</argument>
     </arguments>
    </configuration>
    <dependencies>
     <dependency>
         <groupId>io.github.yangziwen</groupId>
         <artifactId>diff-checkstyle</artifactId>
         <version>0.0.8</version>
         <type>jar</type>
     </dependency>
    </dependencies>
</plugin>
```
and get the following result when run `mvn test -Dcheckstyle.base.rev=HEAD`

<image src="https://user-images.githubusercontent.com/5212414/230523900-2dfe145f-5c48-45c4-9e0c-8986c0693a4c.png" width="400"></image>

**Comment by yangziwen** [comment]
Be awared that diff-check:0.0.8 is not deployed to the maven center repo yet, due to my gpg key expired.
Thus you have to install diff-checkstyle.jar locally or deploy it to your private maven repo before using the  above maven configuration.
I'll fix this problem later.

**Comment by mettyoung** [comment]
Hi @yangziwen how do I specify the base google_checks.xml ?
