### ISSUE TITLE
PMD中文校验乱码

### ISSUE THREAD

**Issue by healzy99** [yangziwen/diff-check#16]
<img width="838" alt="20230729173200" src="https://github.com/yangziwen/diff-check/assets/74692769/076e33e2-dd3b-46c6-a3c5-eae8125b9198">
PMD检查后的提示中文乱码
请问有无命令可以设置编码？

**Comment by yangziwen** [comment]
没有设置字符编码的选项。临时的解决方式，是可以把pmd的输出信息设置为英文（通过设置`git config diff-check.pmd.language en`或`git config --global diff-check.pmd.language en`)

看上去check style输出的中文没问题，但是pmd输出的中文是乱码。你可以尝试直接执行下原生的pmd工具，看输出的结果是否乱码。另外，能告知下你使用的是什么操作系统么？我使用mac，还没有遇到过上面的问题。

此外，可以查看下字符集相关的环境变量`echo $LANG`，我本地的输出结果是“zh_CN.UTF-8”

**Comment by healzy99** [comment]
您好，感谢回复~
我的操作系统是windows 11，字符集相关的环境变量使用的是默认的，但据我了解中国区的windows环境变量都是UTF-8。
我尝试使用临时解决方案，谢谢

**Comment by yangziwen** [comment]
微软社区里貌似也有人反馈遇到windows11部分中文乱码的问题，可以按[win11部分中文乱码](https://answers.microsoft.com/zh-hans/windows/forum/all/win11%E9%83%A8%E5%88%86%E4%B8%AD%E6%96%87%E4%B9%B1/7555acec-aa64-467d-b21c-c898b5cbcf46)中的回复内容再检查下本地区域设置和字符集设置
