### ISSUE TITLE
How can I integrate diff-check to CI ?

### ISSUE THREAD

**Issue by mettyoung** [yangziwen/diff-check#18]
We love the diff-check tool a lot but developers can easily disable it in local. How can we enable this check in CI ?

**Comment by yangziwen** [comment]
Hi mettyoung, thank you for your recognition of this tool. 
Recently I'm really busy and cannot respond to your question raised elsewhere.
It seems there is no out-of-the-box method to integrate this tool into jenkins pipeline just as easy as the original jacoco plugin.
I'll take some days to find how to make diff-check and jenkins pipeline work together, and hope I can provide you some helpful suggestion at that time.

**Comment by mettyoung** [comment]
Oh, thank you so much!


Regards,
Emmett

**Comment by yangziwen** [comment]
I use the following pipeline configuration, and got the build results including diff-checkstyle result and diff-jacoco result.
Be aware that some pipeline plugins(such as git plugin,  code coverage api plugin) are required to preinstall in jenkins.
Hope this demo can bring you some help.

```groovy
pipeline {  
    agent any  
    
    tools {
        maven 'mvn-3.9.4'
    }
  
    stages {
        
        stage('Checkout') {  
            steps {
                git branch: 'diff-check-test-branch', url: 'https://github.com/yangziwen/quick-dao'
            }
        }  
        
        stage('Build and Test') {  
            steps {  
                sh 'mvn clean test -Djacoco.diff.against=origin/master'  
            }  
        }

        stage('Analyze Coverage') {  
            steps {  
                recordCoverage(tools: [[parser: 'JACOCO']],
                    id: 'diff-check-jacoco', name: 'Diff-Check Jacoco Coverage',
                    sourceCodeRetention: 'EVERY_BUILD',
                    qualityGates: [
                            [threshold: 70.0, metric: 'LINE', baseline: 'PROJECT', unstable: true],
                            [threshold: 70.0, metric: 'BRANCH', baseline: 'PROJECT', unstable: true]])
            }  
        }
        
        stage('Check Style') {
            steps {
                sh "curl -L -o diff-checkstyle.jar https://github.com/yangziwen/diff-check/releases/download/0.0.8/diff-checkstyle.jar"
                sh "java -jar ./diff-checkstyle.jar -c /custom_checks.xml ${WORKSPACE} --git-dir ${WORKSPACE} --base-rev=origin/master"
            }
        }
        
    }
}
```
![image](https://github.com/yangziwen/diff-check/assets/5212414/df5d76cf-0c0f-436f-89b5-1514c2c0840a)
![image](https://github.com/yangziwen/diff-check/assets/5212414/6d351b61-70e3-4e16-bd27-8887b60ac2b9)
![image](https://github.com/yangziwen/diff-check/assets/5212414/a41353e8-60ce-45ff-8648-d6010563dfd9)
![image](https://github.com/yangziwen/diff-check/assets/5212414/30be4354-9a44-49db-833e-0e6f80ca6ee0)
![image](https://github.com/yangziwen/diff-check/assets/5212414/1bd85430-9b8d-4e98-9cc6-36b677fe11cb)

**Comment by mettyoung** [comment]
Wow, thank you very much ! Thiis is very helpful !
