### ISSUE TITLE
可以放在gitlab的服务里目录下check吗？

### ISSUE THREAD

**Issue by SoftwareKing** [yangziwen/diff-check#2]
例如:放在:/opt/gitlab/embedded/service/gitlab-shell/hooks

**Comment by yangziwen** [comment]
意思是想做gitlab服务端的代码检查么?

这套工具目前的定位是客户端代码检查，无法直接应用于服务端。
因为git服务端的代码库一般是裸库(bare repo，没有工作区和解压后的源代码)，而checkstyle、pmd的检查都是需要基于源代码的，jacoco的检查则是需要程序打桩运行之后才能输出结果。

我所了解的服务端代码检查的实现方案，一般是通过钩子调用其他程序或与jenkins联动，把当前push的分支的源代码checkout到独立的目录下，再进行检查。同时，这种检查比较耗时，所以一般无法用于阻断push操作，但是可以作为pr是否可以合入的前置判断条件。

**Comment by SoftwareKing** [comment]
![image](https://user-images.githubusercontent.com/6858857/70697848-3b94c600-1d01-11ea-9568-1869c911d178.png)

@yangziwen 试过这种吗

**Comment by yangziwen** [comment]
嗯，看了下，这种方式是可以的，不过他检查的应该是发生过变更的文件的全部问题，里面包含了当前commit未修改过的代码行的问题。

当然，按照diff-check的实现方式，进一步hack下pmd的代码，也是可以按这种思路实现只针对变更过的代码行输出检查结果的效果。

不过这样的钩子实现的稍微有点重(钩子里包含了解压文件、执行检查、清理文件的操作)，如果访问量大的话，这种同步阻塞的检查有可能会给gitlab服务端带来些压力。生产环境下，push的过程和执行代码检查的过程，都有可能涉及到比较显著的cpu消耗。

**Comment by SoftwareKing** [comment]
期待hack一下，方便加个微信交流一下吗？

**Comment by mettyoung** [comment]
Any updates on this? I'm also interested with applying the diff-check to CI pipeline
