### ISSUE TITLE
ali-pmd检查结果乱码

### ISSUE THREAD

**Issue by huangdada12** [yangziwen/diff-check#5]
git commit使用ali_all.xml。输出的检查日志乱码，控制台其他中文没乱码
![Uploading 企业微信截图_16418823094885.png…]()

**Comment by yangziwen** [comment]
谢谢反馈，我会尽快找时间查看下的~

**Comment by huangdada12** [comment]
> 

感谢，请问源码当中可以设置p3c-pmd检查的输出日志为英文版本的吗

**Comment by yangziwen** [comment]
我没能复现中文乱码的问题
但是通过修改pre-commit-pmd脚本中如下内容，可以使输出结果变为英文
pre-commit-pmd可能在当前工程的`.git`目录中（如果是指定代码库安装），或者家目录的`~/.githooks`目录中（如果是全局安装）
![image](https://user-images.githubusercontent.com/5212414/149118584-01484122-2f3d-4170-b753-4a7202986edc.png)
![image](https://user-images.githubusercontent.com/5212414/149119713-8f10f4e5-adc0-4e39-9b61-c0914e0a2836.png)

**Comment by yangziwen** [comment]
昨天更新了下脚本和readme，如果安装最新的钩子脚本，并按如下方式设置语言选项，就可以切换中文和英文了
不过pmd只支持中文和英文，checkstyle支持的语言会多一些
![image](https://user-images.githubusercontent.com/5212414/149264315-c043c9f5-8cc8-4fdd-9638-1dccd84fbaf4.png)

**Comment by huangdada12** [comment]
感谢大佬
