### ISSUE TITLE
豁免路径的设置

### ISSUE THREAD

**Issue by huangdada12** [yangziwen/diff-check#8]
git config diff-check.pmd.exclude-regexp .+-client/.*
关于豁免路径的设置，可以来个样例吗，直接在脚本里面设置没匹配到

**Comment by yangziwen** [comment]
这个配置本质上就是用正则表达式来匹配想豁免的代码路径

可以把你工程里想豁免的目录路径贴出来，我周末给个对应的豁免配置的写法

**Comment by huangdada12** [comment]
![image](https://user-images.githubusercontent.com/59047844/150106828-69472887-255e-4829-98a1-0dc7511425b8.png)
目标项目是多模块的项目，想豁免左边目录下的，直接把路径写在脚本里面，团队直接使用，不单独配置git，按你说的方式没有实现

**Comment by yangziwen** [comment]
是否方便把上面右侧截图的整个脚本贴出来我看下~

**Comment by huangdada12** [comment]
`
#!/bin/bash
# hook.version@1.0.0

GIT_ROOT_DIR=`git rev-parse --show-toplevel`
PDM_DIR="/.githooks/validate-code/diff-pmd.jar"
if [ ! -f "${GIT_ROOT_DIR}${PDM_DIR}" ]; then
    echo "diff-pmd.jar does not exist!"
    exit 1
fi

# check whether this is the first commit
git log --oneline -1 > /dev/null 2>&1
result=$?
if [ $result -ne 0 ]; then
    exit 0
fi

#忽略不需要pmd�?查的文件路径
exclude_regexp_opt="-exclude-regexp (.*/generated/.*)"


pmd_rulesets="`git config --get diff-check.pmd.rulesets`"
if [ -z "$pmd_rulesets" ]; then
    pmd_rulesets="rulesets/java/ali-all.xml"
fi

echo "PMD Check"
java -Dpmd.language=en -jar ${GIT_ROOT_DIR}${PDM_DIR} -R $pmd_rulesets -f diff-text -git-dir ${GIT_ROOT_DIR} -include-staged-codes $exclude_regexp_opt
result=$?
if [ $result -ne 0 ]; then
    echo "请在提交之前修复pmd问题"
    exit $result
fi

exit 0
`
就是你项目的里面的脚本改造了一下

**Comment by huangdada12** [comment]
#!/bin/bash
# hook.version@1.0.0

GIT_ROOT_DIR=`git rev-parse --show-toplevel`
PDM_DIR="/.githooks/validate-code/diff-pmd.jar"
if [ ! -f "${GIT_ROOT_DIR}${PDM_DIR}" ]; then
    echo "diff-pmd.jar does not exist!"
    exit 1
fi

# check whether this is the first commit
git log --oneline -1 > /dev/null 2>&1
result=$?
if [ $result -ne 0 ]; then
    exit 0
fi

#忽略不需要pmd�?查的文件路径
exclude_regexp_opt="-exclude-regexp (.*/generated/.*)"


pmd_rulesets="`git config --get diff-check.pmd.rulesets`"
if [ -z "$pmd_rulesets" ]; then
    pmd_rulesets="rulesets/java/ali-all.xml"
fi

echo "PMD Check"
java -Dpmd.language=en -jar ${GIT_ROOT_DIR}${PDM_DIR} -R $pmd_rulesets -f diff-text -git-dir ${GIT_ROOT_DIR} -include-staged-codes $exclude_regexp_opt
result=$?
if [ $result -ne 0 ]; then
    echo "请在提交之前修复pmd问题"
    exit $result
fi

exit 0

就是你项目里面的脚本稍微改了一下

**Comment by yangziwen** [comment]
`exclude_regexp_opt="-exclude-regexp '(.*/generated/.*)'"`
括号的左右加上单引号和星号试试`'(.*/generated/.*)'`
要通过.*匹配前后的多个字符

**Comment by huangdada12** [comment]
是加了的，可能是复制出来没显示，这样配置路径没有过滤到

**Comment by yangziwen** [comment]
你是用的linux或者mac么？还是windows？

**Comment by yangziwen** [comment]
> 是加了的，可能是复制出来没显示，这样配置路径没有过滤到

要不还是把完整的文件作为附件上传上来吧
不然看到的内容跟你实际写的内容不一致，很难确定问题出在哪里
