### ISSUE TITLE
关于增量代码的设置问题

### ISSUE THREAD

**Issue by SmallPiedPiper** [yangziwen/diff-check#9]
运行checkstyle的的增量代码检测，这里的增量代码是值得 当前文件当中变更了那些代码行吗？还是说增量代码值得是 变更的哪些文件呢？因为我这边存在大量老工程，老文件存量问题是难以处理的，相对增量代码行进行处理？

Run checkstyle's incremental code detection. Is the incremental code worth it? Are those lines of code changed in the current file? Or which files are the incremental code worth changing? Because there are a lot of old projects on my side, the problem of old file inventory is difficult to deal with, how about dealing with incremental lines of code?

**Comment by yangziwen** [comment]
增量检查针对的不是发生变更的文件，而是具体到那些发生了变更的代码行。

也就是说，在指定提交范围内发生了变更的文件，其中那些未被修改的代码行，即使不符合checkstyle规范，也会被忽略掉，不会输出问题扫描结果和阻碍git提交。

当时开发这个工具，也是为了用在老工程上，跟你目前的诉求应该是一致的。

这里有一个diff-check前身的文档([diff-checkstyle](https://github.com/yangziwen/diff-checkstyle/blob/master/README_CN.md))，也许对你有帮助。

**Comment by SmallPiedPiper** [comment]
您这改造的jar包文件是在原有的checkstyle.jar文件基础之上改造的吗  方便了解下您当初是对那些文件作出了改变吗？了解下这个实现的部分

**Comment by yangziwen** [comment]
重新实现了下checkstyle的Main类，并追加了一个基于变更行内容进行输出结果过滤的filter。
详情可以看下[这个包](https://github.com/yangziwen/diff-check/tree/master/diff-checkstyle/src/main/java/io/github/yangziwen/checkstyle)下的内容

**Comment by SmallPiedPiper** [comment]
奥奥 老哥这个真解决了一个痛点问题呀，我还在看具体的实现逻辑，你们是已经在生产环境用了吗？

**Comment by yangziwen** [comment]
这个工具三年前开发，当时在三十多人的团队里使用过一段时间，都是在研发人员的电脑上作为客户端使用。

后来公司的代码平台提供了类似的功能，因此无需研发人员在客户端进行增量代码风格检查了，所以也就一直没有升级该工具所依赖的checkstyle的版本，目前版本有点旧。

另外需要注意的是，本工具依赖代码文件的实际内容，所以无法用于裸库（[bare git repository](https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server)）。
